SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[studentTable](
	[student#] [bigint] NOT NULL,
	[studentFName] [text] COLLATE Persian_100_CI_AS NOT NULL,
	[studentLName] [text] COLLATE Persian_100_CI_AS NOT NULL,
	[studentURL] [text] COLLATE Persian_100_CI_AS NULL,
 CONSTRAINT [PK_studentTable] PRIMARY KEY CLUSTERED 
(
	[student#] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
